version: "3"
services:
  web.localhost:
    container_name: web
    image: node:20-alpine3.18
    ports:
      - 3000:3000
    depends_on:
      - idp.localhost
    volumes:
      - ./web:/app
    tty: true
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - |
        npm install;
        npm run dev;
  idp.localhost:
    container_name: idp
    image: bitnami/keycloak:24
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN_USER: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KEYCLOAK_DATABASE_HOST: db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: bitnami_keycloak
      KEYCLOAK_DATABASE_USER: bn_keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
    depends_on:
      - db
      - smtp.localhost
  db:
    container_name: db
    image: postgres:16.3
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitnami_keycloak
    volumes:
      - ./db/data:/var/lib/postgresql/data
  smtp.localhost:
    container_name: smtp
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  gqle.localhost:
    container_name: gqle
    image: hasura/graphql-engine:v2.39.0
    ports:
      - "8180:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://bn_keycloak:password@db:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: XLpbQ2xHghijY7Wsn5ObTP4AsDHuVkW4
    depends_on:
      - db